### ISSUE TITLE
Local Import Issue

### ISSUE THREAD

**Issue by jrafaaael** [Renovamen/oh-vue-icons#13]
The documentation states that, to perform a local import, the path must be placed: `"oh-vue-icons/components/icon"`

But the "components" folder does not exist when downloading, at least when downloading the module through npm.

![image](https://user-images.githubusercontent.com/70046023/116249156-84a0bb00-a73a-11eb-8cd5-ddb3fd332329.png)

**Comment by vicenterusso** [comment]
Maybe because [0.4.1](https://github.com/Renovamen/oh-vue-icons/releases/tag/v0.4.1) changed a few things

This is how I'm using after updating:
```js
import OhVueIcon from 'oh-vue-icons';
import {LaThSolid,LaBarsSolid,RiRefreshLine} from 'oh-vue-icons/icons';
OhVueIcon.add(LaThSolid, LaBarsSolid, RiRefreshLine);

export default {
    components: {
        'v-oh-icon': OhVueIcon
    },
    // {...}
}
```

**Comment by jrafaaael** [comment]
> This is how I'm using after updating:

Thanks! At the moment I use it with the global import. Similarly, the documentation should be updated. I hope it is solved soon😄

**Comment by Renovamen** [comment]
Hi @jrafaaael @vicenterusso! I forgot to update the documentation, sorry for that. Now the documentation has been updated, thank you!
