### ISSUE TITLE
Using oh-vue-icons with NuxtJS

### ISSUE THREAD

**Issue by cryptic-ai** [Renovamen/oh-vue-icons#15]
I'm having an issue getting this set up with nuxtjs.

I have the following in `~/plugins/icons.ts`:

```ts
import Vue from "vue";
import OhVueIcon from 'oh-vue-icons';

import {
  FaFlag
} from "oh-vue-icons/icons/fa";

OhVueIcon.add(FaFlag);

Vue.component("v-icon", OhVueIcon);
```

Then my `nuxt.config.ts`:

```ts
...
  plugins: [
    '~/plugins/apollo.ts',
    '~/plugins/icons.ts'
  ],
...

  build: {
    transpile: [/oh-vue-icons/],
  }
```

I have also tried

```ts
transpile: ["oh-vue-icons"]
```

I get the following error:

![image](https://user-images.githubusercontent.com/11448029/125537091-dfb4b1c2-c19e-4d5f-a8d3-d1c536711e27.png)

Any idea why it's not working?

**Comment by plushugh** [comment]
Had the same problem with nuxt
![image](https://user-images.githubusercontent.com/46068081/125598332-afec525d-451a-4104-9157-b549e70a0edb.png)

**Comment by Renovamen** [comment]
@cryptic-ai @plushugh Hi, some critical files are missed in v0.4.4 due to my mistake when publishing it, sorry for that. The problem has been fixed in v0.4.5, thank you!

**Comment by cryptic-ai** [comment]
Awesome thank you so much! Fantastic library!

**Comment by cryptic-ai** [comment]
Just coming back to verify that the issue is fixed in `v.0.4.5`. Thanks again!
