### ISSUE TITLE
Compatibility with NuxtJS

### ISSUE THREAD

**Issue by ghostlexly** [Renovamen/oh-vue-icons#3]
Hello,

Is there any way to make it compatible with NuxtJS ?

Thanks

**Comment by Renovamen** [comment]
Hi @ghostlexly, if you are using Nuxt for server side rendering, maybe you need to add this package to the transpile build option in `nuxt.config.js`:

```js
export default {
  // ...
  build: {
    transpile: ['oh-vue-icons']
  }
}
```

or Nuxt will not bundle it, see [Nuxt's docs](https://nuxtjs.org/docs/2.x/directory-structure/plugins) for details.

Sorry I forgot to mention this in docs, I'll add it later, thanks for you issue.

**Comment by ghostlexly** [comment]
Hello,
Thank you for your fast reply.
It is working great but a error occur :

![image](https://user-images.githubusercontent.com/62400734/109301133-c7780c80-7837-11eb-82a9-79a1165028a2.png)

**Comment by Renovamen** [comment]
Oh, I haven't encountered such an error, but maybe it's because `core-js` is also transpiled.

However, this package doesn't need `core-js` actually, it's my fault to add it to dependencies, sorry again. I'll remove it in the next release. 😂

**Comment by Renovamen** [comment]
`core-js` is removed in v0.1.11, take a look at it?
