### ISSUE TITLE
Suggestion: add typescript declarations

### ISSUE THREAD

**Issue by redsuperbat** [Renovamen/oh-vue-icons#6]
Currently trying to install this in a vue3 ts project. Since there is no declaration file it is making it harder than it should be.

If anyone else has this problem just add this line of code to a shim file:
```typescript
declare module "oh-vue-icons/*";
```

**Comment by Renovamen** [comment]
Hi! Typescript declaration files have been added in v0.3.0, so I guess it will work well in typescript now. Thanks you for the suggetion!

So I'm closing this now.
