### ISSUE TITLE
Bundle size is huge in version 0.3.1

### ISSUE THREAD

**Issue by redsuperbat** [Renovamen/oh-vue-icons#9]
Tried upgrading from v 0.2.1 -> 0.3.1 and suddenly the bundle size of the vue3 component increased by 77kb (which is A LOT). Wondering if there is some exports configured incorrectly perhaps? 

Version 0.3.1: 
![Screenshot from 2021-03-26 15-15-46](https://user-images.githubusercontent.com/44667637/112644872-2dab7b80-8e46-11eb-91fe-20b9d04b3157.png)

Version 0.2.1:
![Screenshot from 2021-03-26 15-16-30](https://user-images.githubusercontent.com/44667637/112644954-4582ff80-8e46-11eb-8711-26f3663991ce.png)

**Comment by Renovamen** [comment]
Oh, I see... I bundled the component using umd format since v0.3, which doesn't support tree-shaking. Maybe I should use es format. I'll have a try, thank you!

**Comment by Renovamen** [comment]
Now I move to rollup and the esm format bundle is available. In my test, the bundle size will not increase (that much). Could you take a look at v0.4.1?

Import the component in Vue 3 by:

```js
import OhVueIcon from "oh-vue-icons/dist/v3/icon.es";
```

**Comment by redsuperbat** [comment]
Perfect! Works as intended now!
